package com.equipo2.Appkademy.rest.error;

public class ErrorCodes {

    public static final String HOURLY_RATES_CANNOT_BE_NULL_OR_EMPTY = "HOURLY_RATES_CANNOT_BE_NULL_OR_EMPTY";
    public static final String FIRST_NAME_CANNOT_BE_NULL_OR_EMPTY = "FIRST_NAME_CANNOT_BE_NULL_OR_EMPTY";
    public static final String LAST_NAME_CANNOT_BE_NULL_OR_EMPTY = "LAST_NAME_CANNOT_BE_NULL_OR_EMPTY";
    public static final String EMAIL_CANNOT_BE_NULL_OR_EMPTY = "EMAIL_CANNOT_BE_NULL_OR_EMPTY";

    public static final String SHORT_DESCRIPTION_CANNOT_BE_NULL_OR_EMPTY = "EMAIL_CANNOT_BE_NULL_OR_EMPTY";

    public static final String FULL_DESCRIPTION_CANNOT_BE_NULL_OR_EMPTY = "FULL_DESCRIPTION_CANNOT_BE_NULL_OR_EMPTY";
    public static final String ADDRESS_CANNOT_BE_NULL = "ADDRESS_CANNOT_BE_NULL";

    public static final String MODALITIES_CANNOT_BE_NULL_OR_EMPTY = "MODALITIES_CANNOT_BE_NULL_OR_EMPTY";
    public static final String PROFICIENCIES_CANNOT_BE_NULL_OR_EMPTY = "PROFICIENCIES_CANNOT_BE_NULL_OR_EMPTY";
    public static final String WEEKLY_WORKING_SCHEDULE_CANNOT_BE_NULL = "WEEKLY_WORKING_SCHEDULE_CANNOT_BE_NULL";

    public static final String COUNTRY_CANNOT_BE_NULL_OR_EMPTY = "COUNTRY_CANNOT_BE_NULL_OR_EMPTY";

    public static final String PROVINCE_CANNOT_BE_NULL_OR_EMPTY = "PROVINCE_CANNOT_BE_NULL_OR_EMPTY";

    public static final String CITY_CANNOT_BE_NULL_OR_EMPTY = "CITY_CANNOT_BE_NULL_OR_EMPTY";

    public static final String STREET_NAME_CANNOT_BE_NULL_OR_EMPTY = "STREET_NAME_CANNOT_BE_NULL_OR_EMPTY";

    public static final String STREET_NUMBER_CANNOT_BE_NULL_OR_EMPTY = "STREET_NUMBER_CANNOT_BE_NULL_OR_EMPTY";

    public static final String CHECK_IN_CANNOT_BE_NULL = "CHECK_IN_CANNOT_BE_NULL";

    public static final String CHECK_OUT_CANNOT_BE_NULL = "CHECK_OUT_CANNOT_BE_NULL";

    public static final String STARTS_ON_CANNOT_BE_NULL = "STARTS_ON_CANNOT_BE_NULL";

    public static final String ENDS_ON_CANNOT_BE_NULL = "ENDS_ON_CANNOT_BE_NULL";

    public static final String PROVIDER_ID_CANNOT_BE_NULL = "PROVIDER_ID_CANNOT_BE_NULL";

    public static final String CUSTOMER_ID_CANNOT_BE_NULL = "CUSTOMER_ID_CANNOT_BE_NULL";

}
